---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/nautobot-plugin-device42-sync/docs"
site_name: "NautobotDevice42Sync Documentation"
site_url: "https://nautobot-plugin-device42-sync.readthedocs.io/"
repo_url: "https://gitlab.corp.zmi.global/networking/nautobot-plugin-device42-sync.git"
python:
  install:
    - requirements: "docs/requirements.txt"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
nav:
  - Introduction: "index.md"
